// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2F-yeCgbDOH69fOu4r6N-8wXv3Cr0KwA',
    appId: '1:405114655528:web:f9a01a88dd71963451761d',
    messagingSenderId: '405114655528',
    projectId: 'agri-auction-house',
    authDomain: 'agri-auction-house.firebaseapp.com',
    storageBucket: 'agri-auction-house.firebasestorage.app',
    measurementId: 'G-8NG2QM4Y5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgL8sGQiyAx6BHmqKttMBoiDERxLpOVAE',
    appId: '1:405114655528:android:37e5f79d8c2168c851761d',
    messagingSenderId: '405114655528',
    projectId: 'agri-auction-house',
    storageBucket: 'agri-auction-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2nsMky1z1F7cBEkzDCD_1da6Yt3m4SSc',
    appId: '1:405114655528:ios:db11a1ebfb103b5f51761d',
    messagingSenderId: '405114655528',
    projectId: 'agri-auction-house',
    storageBucket: 'agri-auction-house.firebasestorage.app',
    iosBundleId: 'com.example.agriAuctionHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2nsMky1z1F7cBEkzDCD_1da6Yt3m4SSc',
    appId: '1:405114655528:ios:db11a1ebfb103b5f51761d',
    messagingSenderId: '405114655528',
    projectId: 'agri-auction-house',
    storageBucket: 'agri-auction-house.firebasestorage.app',
    iosBundleId: 'com.example.agriAuctionHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2F-yeCgbDOH69fOu4r6N-8wXv3Cr0KwA',
    appId: '1:405114655528:web:7b60a34b7c518f9751761d',
    messagingSenderId: '405114655528',
    projectId: 'agri-auction-house',
    authDomain: 'agri-auction-house.firebaseapp.com',
    storageBucket: 'agri-auction-house.firebasestorage.app',
    measurementId: 'G-DZVQSVJS1C',
  );
}
